#:kivy 2.0.0

<ScreenOne>:
    GridLayout:
        cols: 1
        padding: 5
        space: 5
        Image:
            id: image_for_screen
            size_hint_y: 0.8
        TextInput: 
            id : user_input
            size_hint_y: 0.1
        Button:
            text: 'Search Image'
            size_hint_y: 0.1
            on_press: root.search_img() 

<RootWidgets>:
    ScreenOne:
        id: first_screen
        name: 'first_screen'
